title: "Blogs"
author: "Colin McQueen"
description: "Vulnerabilities discovered and exploited during my career."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false
show_frame: true
show_sidebar: false
show_minimal: false

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", sidebaricon: home}
  - {file: "README.md", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/colinamcqueen"}
  - {title: GitHub, icon: github, url: "https://github.com/ArgentEnergy"}
  - {title: Bugcrowd, icon: bug, url: "https://bugcrowd.com/h/argentenergy"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
